const VOCABULARY = [
{it:"voce",de:"Stimme",cat:"Substantive"},
{it:"nome",de:"Name",cat:"Substantive"},
{it:"sera",de:"Abend",cat:"Substantive"},
{it:"acqua",de:"Wasser",cat:"Substantive"},
{it:"amico",de:"Freund",cat:"Substantive"},
{it:"fatto",de:"Erledigt",cat:"Substantive"},
{it:"gente",de:"Menschen",cat:"Substantive"},
{it:"amore",de:"Liebe",cat:"Substantive"},
{it:"storia",de:"Geschichte",cat:"Substantive"},
{it:"aria",de:"Luft",cat:"Substantive"},
{it:"forza",de:"Leistung",cat:"Substantive"},
{it:"testa",de:"Kopf",cat:"Substantive"},
{it:"ragione",de:"Grund",cat:"Substantive"},
{it:"mare",de:"Meer",cat:"Substantive"},
{it:"mese",de:"Monat",cat:"Substantive"},
{it:"capo",de:"Kopf",cat:"Substantive"},
{it:"luce",de:"Licht",cat:"Substantive"},
{it:"sole",de:"Sonne",cat:"Substantive"},
{it:"famiglia",de:"Familie",cat:"Substantive"},
{it:"piede",de:"Fuß",cat:"Substantive"},
{it:"persona",de:"Person",cat:"Substantive"},
{it:"via",de:"Straße",cat:"Substantive"},
{it:"signora",de:"Frau",cat:"Substantive"},
{it:"governo",de:"Regierung",cat:"Substantive"},
{it:"senso",de:"Sinn",cat:"Substantive"},
{it:"opera",de:"Oper",cat:"Substantive"},
{it:"prodotto",de:"Produkt",cat:"Substantive"},
{it:"festa",de:"Party",cat:"Substantive"},
{it:"gioco",de:"Spiel",cat:"Substantive"},
{it:"politica",de:"Politik",cat:"Substantive"},
{it:"processo",de:"Verfahren",cat:"Substantive"},
{it:"vino",de:"Wein",cat:"Substantive"},
{it:"porta",de:"Tür",cat:"Substantive"},
{it:"sud",de:"Süden",cat:"Substantive"},
{it:"sogno",de:"Traum",cat:"Substantive"},
{it:"cane",de:"Hund",cat:"Substantive"},
{it:"isola",de:"Insel",cat:"Substantive"},
{it:"movimento",de:"Bewegung",cat:"Substantive"},
{it:"mente",de:"Geist",cat:"Substantive"},
{it:"occasione",de:"Gelegenheit",cat:"Substantive"},
{it:"prezzo",de:"Preis",cat:"Substantive"},
{it:"causa",de:"Ursache",cat:"Substantive"},
{it:"periodo",de:"Zeitraum",cat:"Substantive"},
{it:"sviluppo",de:"Entwicklung",cat:"Substantive"},
{it:"sorella",de:"Schwester",cat:"Substantive"},
{it:"effetto",de:"Wirkung",cat:"Substantive"},
{it:"giardino",de:"Garten",cat:"Substantive"},
{it:"attività",de:"Aktivitäten",cat:"Substantive"},
{it:"volontà",de:"Wille",cat:"Substantive"},
{it:"volto",de:"Gesicht",cat:"Substantive"},
{it:"base",de:"Basis",cat:"Substantive"},
{it:"carattere",de:"Charakter",cat:"Substantive"},
{it:"coscienza",de:"Bewusstsein",cat:"Substantive"},
{it:"guardia",de:"bewachen",cat:"Substantive"},
{it:"memoria",de:"Erinnerung",cat:"Substantive"},
{it:"terreno",de:"Boden",cat:"Substantive"},
{it:"animale",de:"Tier",cat:"Substantive"},
{it:"direzione",de:"Richtung",cat:"Substantive"},
{it:"ferro",de:"Eisen",cat:"Substantive"},
{it:"punta",de:"Tipp",cat:"Substantive"},
{it:"regno",de:"Königreich",cat:"Substantive"},
{it:"epoca",de:"Epoche",cat:"Substantive"},
{it:"luna",de:"Mond",cat:"Substantive"},
{it:"provincia",de:"Provinz",cat:"Substantive"},
{it:"voglia",de:"Wunsch",cat:"Substantive"},
{it:"differenza",de:"Unterschied",cat:"Substantive"},
{it:"controllo",de:"Kontrolle",cat:"Substantive"},
{it:"grazia",de:"Anmut",cat:"Substantive"},
{it:"passato",de:"Vergangenheit",cat:"Substantive"},
{it:"spazio",de:"Raum",cat:"Substantive"},
{it:"stella",de:"Stern",cat:"Substantive"},
{it:"corsa",de:"Wettrennen",cat:"Substantive"},
{it:"erba",de:"Gras",cat:"Substantive"},
{it:"massa",de:"Masse",cat:"Substantive"},
{it:"origine",de:"Herkunft",cat:"Substantive"},
{it:"polizia",de:"Polizei",cat:"Substantive"},
{it:"soluzione",de:"Lösung",cat:"Substantive"},
{it:"chilometro",de:"Kilometer",cat:"Substantive"},
{it:"madre",de:"Mutter",cat:"Substantive"},
{it:"paura",de:"Furcht",cat:"Substantive"},
{it:"cuore",de:"Herz",cat:"Substantive"},
{it:"idea",de:"Idee",cat:"Substantive"},
{it:"fondo",de:"Hintergrund",cat:"Substantive"},
{it:"esempio",de:"Beispiel",cat:"Substantive"},
{it:"ordine",de:"Befehl",cat:"Substantive"},
{it:"posto",de:"Ort",cat:"Substantive"},
{it:"campo",de:"Feld",cat:"Substantive"},
{it:"condizione",de:"Zustand",cat:"Substantive"},
{it:"professore",de:"Lehrer",cat:"Substantive"},
{it:"marito",de:"Ehemann",cat:"Substantive"},
{it:"verità",de:"Wahrheit",cat:"Substantive"},
{it:"segno",de:"Zeichen",cat:"Substantive"},
{it:"diritto",de:"Rechts",cat:"Substantive"},
{it:"lettera",de:"Brief",cat:"Substantive"},
{it:"ragazza",de:"Mädchen",cat:"Substantive"},
{it:"scuola",de:"Schule",cat:"Substantive"},
{it:"camera",de:"Zimmer",cat:"Substantive"},
{it:"gruppo",de:"Gruppe",cat:"Substantive"},
{it:"discorso",de:"Rede",cat:"Substantive"},
{it:"centro",de:"Center",cat:"Substantive"},
{it:"secolo",de:"Jahrhundert",cat:"Substantive"},
{it:"mezzo",de:"Hälfte",cat:"Adjektive"},
{it:"tipo",de:"Kerl",cat:"Substantive"},
{it:"colpa",de:"Fehler",cat:"Substantive"},
{it:"rispetto",de:"respektieren",cat:"Substantive"},
{it:"scena",de:"Szene",cat:"Substantive"},
{it:"oggetto",de:"Objekt",cat:"Substantive"},
{it:"possibilità",de:"Wahrscheinlichkeit",cat:"Substantive"},
{it:"mamma",de:"Mama",cat:"Substantive"},
{it:"presenza",de:"Gegenwart",cat:"Substantive"},
{it:"teatro",de:"Theater",cat:"Substantive"},
{it:"caffè",de:"Kaffee",cat:"Substantive"},
{it:"principio",de:"Prinzip",cat:"Substantive"},
{it:"termine",de:"Begriff",cat:"Substantive"},
{it:"lingua",de:"Zunge",cat:"Substantive"},
{it:"pezzo",de:"Stück",cat:"Substantive"},
{it:"autorità",de:"Behörde",cat:"Substantive"},
{it:"gamba",de:"Bein",cat:"Substantive"},
{it:"patria",de:"Heimat",cat:"Substantive"},
{it:"albergo",de:"Hotel",cat:"Substantive"},
{it:"gioia",de:"Freude",cat:"Substantive"},
{it:"argomento",de:"Thema",cat:"Substantive"},
{it:"sguardo",de:"sehen",cat:"Substantive"},
{it:"relazione",de:"Bericht",cat:"Substantive"},
{it:"classe",de:"Klasse",cat:"Substantive"},
{it:"battaglia",de:"Schlacht",cat:"Substantive"},
{it:"viso",de:"Gesicht",cat:"Substantive"},
{it:"gesto",de:"Geste",cat:"Substantive"},
{it:"mattino",de:"Morgen",cat:"Substantive"},
{it:"opinione",de:"Meinung",cat:"Substantive"},
{it:"ponte",de:"Brücke",cat:"Substantive"},
{it:"sorriso",de:"lächeln",cat:"Substantive"},
{it:"frase",de:"Phrase",cat:"Substantive"},
{it:"limite",de:"Limit",cat:"Substantive"},
{it:"ritorno",de:"zurückkehren",cat:"Substantive"},
{it:"bosco",de:"Holz",cat:"Substantive"},
{it:"esame",de:"Prüfung",cat:"Substantive"},
{it:"lato",de:"Seite",cat:"Substantive"},
{it:"operazione",de:"Betrieb",cat:"Substantive"},
{it:"pranzo",de:"Mittagessen",cat:"Substantive"},
{it:"costa",de:"es kostet",cat:"Substantive"},
{it:"prato",de:"Wiese",cat:"Substantive"},
{it:"repubblica",de:"Republik",cat:"Substantive"},
{it:"valle",de:"Schlucht",cat:"Substantive"},
{it:"nord",de:"Norden",cat:"Substantive"},
{it:"cortile",de:"Hof",cat:"Substantive"},
{it:"pelle",de:"Haut",cat:"Substantive"},
{it:"proposta",de:"Vorschlag",cat:"Substantive"},
{it:"riva",de:"Ufer",cat:"Substantive"},
{it:"segretario",de:"Sekretär",cat:"Substantive"},
{it:"abito",de:"Kleid",cat:"Substantive"},
{it:"chiave",de:"Schlüssel",cat:"Substantive"},
{it:"corrente",de:"aktuell",cat:"Substantive"},
{it:"operaio",de:"Arbeitnehmer",cat:"Substantive"},
{it:"corso",de:"Kurs",cat:"Substantive"},
{it:"finestra",de:"Fenster",cat:"Substantive"},
{it:"arte",de:"Kunst",cat:"Substantive"},
{it:"sistema",de:"System",cat:"Substantive"},
{it:"piano",de:"planen",cat:"Substantive"},
{it:"bocca",de:"Mund",cat:"Substantive"},
{it:"anima",de:"Seele",cat:"Substantive"},
{it:"palazzo",de:"Palast",cat:"Substantive"},
{it:"passo",de:"Schritt",cat:"Substantive"},
{it:"giornata",de:"Tag",cat:"Substantive"},
{it:"servizio",de:"Service",cat:"Substantive"},
{it:"rapporto",de:"Beziehung",cat:"Substantive"},
{it:"milione",de:"Million",cat:"Substantive"},
{it:"stanza",de:"Zimmer",cat:"Substantive"},
{it:"valore",de:"Wert",cat:"Substantive"},
{it:"colpo",de:"Schlag",cat:"Substantive"},
{it:"sangue",de:"Blut",cat:"Substantive"},
{it:"interesse",de:"Interesse",cat:"Substantive"},
{it:"spalla",de:"Schulter",cat:"Substantive"},
{it:"silenzio",de:"Schweigen",cat:"Substantive"},
{it:"settimana",de:"Woche",cat:"Substantive"},
{it:"notizia",de:"Nachricht",cat:"Substantive"},
{it:"fratello",de:"Bruder",cat:"Substantive"},
{it:"realtà",de:"Wirklichkeit",cat:"Substantive"},
{it:"industria",de:"Industrie",cat:"Substantive"},
{it:"piacere",de:"mögen",cat:"Verben"},
{it:"maestro",de:"Master",cat:"Substantive"},
{it:"personaggio",de:"Charakter",cat:"Substantive"},
{it:"pomeriggio",de:"Nachmittag",cat:"Substantive"},
{it:"fianco",de:"Seite",cat:"Substantive"},
{it:"bambina",de:"Kind",cat:"Substantive"},
{it:"bellezza",de:"Schönheit",cat:"Substantive"},
{it:"domanda",de:"Frage",cat:"Substantive"},
{it:"pianta",de:"Anlage",cat:"Substantive"},
{it:"pubblico",de:"öffentlich",cat:"Adjektive"},
{it:"sede",de:"Sitz",cat:"Substantive"},
{it:"affare",de:"handeln",cat:"Substantive"},
{it:"bene",de:"Also",cat:"Sonstige"},
{it:"metà",de:"Hälfte",cat:"Substantive"},
{it:"papà",de:"Papst",cat:"Substantive"},
{it:"fiume",de:"Fluss",cat:"Substantive"},
{it:"lotta",de:"kämpfen",cat:"Substantive"},
{it:"mercato",de:"Markt",cat:"Substantive"},
{it:"angolo",de:"Winkel",cat:"Substantive"},
{it:"compagnia",de:"Unternehmen",cat:"Substantive"},
{it:"espressione",de:"Ausdruck",cat:"Substantive"},
{it:"labbro",de:"Lippe",cat:"Substantive"},
{it:"villa",de:"Villa",cat:"Substantive"},
{it:"desiderio",de:"Wunsch",cat:"Substantive"},
{it:"giovanotto",de:"junger Mann",cat:"Substantive"},
{it:"poeta",de:"Dichter",cat:"Substantive"},
{it:"stagione",de:"Jahreszeit",cat:"Substantive"},
{it:"peso",de:"Gewicht",cat:"Substantive"},
{it:"tono",de:"Ton",cat:"Substantive"},
{it:"croce",de:"kreuzen",cat:"Substantive"},
{it:"decisione",de:"Entscheidung",cat:"Substantive"},
{it:"poesia",de:"Poesie",cat:"Substantive"},
{it:"fiducia",de:"Vertrauen",cat:"Substantive"},
{it:"filo",de:"Draht",cat:"Substantive"},
{it:"folla",de:"Menge",cat:"Substantive"},
{it:"qualità",de:"Qualität",cat:"Substantive"},
{it:"roba",de:"Sachen",cat:"Substantive"},
{it:"conoscenza",de:"Wissen",cat:"Substantive"},
{it:"favore",de:"favorisieren",cat:"Substantive"},
{it:"popolazione",de:"Bevölkerung",cat:"Substantive"},
{it:"strumento",de:"Werkzeug",cat:"Substantive"},
{it:"uso",de:"verwenden",cat:"Substantive"},
{it:"vestito",de:"Kleid",cat:"Substantive"},
{it:"commercio",de:"Geschäft",cat:"Substantive"},
{it:"fabbrica",de:"Fabrik",cat:"Substantive"},
{it:"giugno",de:"Juni",cat:"Substantive"},
{it:"giustizia",de:"Gerechtigkeit",cat:"Substantive"},
{it:"avvocato",de:"Rechtsanwalt",cat:"Substantive"},
{it:"messa",de:"Masse",cat:"Substantive"},
{it:"orecchio",de:"Ohr",cat:"Substantive"},
{it:"sonno",de:"schlafen",cat:"Substantive"},
{it:"congresso",de:"Kongress",cat:"Substantive"},
{it:"porto",de:"Hafen",cat:"Substantive"},
{it:"calcio",de:"Fußball",cat:"Substantive"},
{it:"fantasia",de:"Fantasie",cat:"Substantive"},
{it:"matrimonio",de:"Hochzeit",cat:"Substantive"},
{it:"medico",de:"Arzt",cat:"Substantive"},
{it:"ospedale",de:"Krankenhaus",cat:"Substantive"},
{it:"pianura",de:"flaches Land",cat:"Substantive"},
{it:"tavolo",de:"Tisch",cat:"Substantive"},
{it:"fame",de:"Hunger",cat:"Substantive"},
{it:"latte",de:"Milch",cat:"Substantive"},
{it:"merito",de:"Verdienst",cat:"Substantive"},
{it:"attore",de:"Schauspieler",cat:"Substantive"},
{it:"ricchezza",de:"Reichtum",cat:"Substantive"},
{it:"sacrificio",de:"opfern",cat:"Substantive"},
{it:"atteggiamento",de:"Attitüde",cat:"Substantive"},
{it:"concetto",de:"Konzept",cat:"Substantive"},
{it:"mestiere",de:"Handwerk",cat:"Substantive"},
{it:"attesa",de:"Warten",cat:"Substantive"},
{it:"bagno",de:"Badezimmer",cat:"Substantive"},
{it:"foglia",de:"Blatt",cat:"Substantive"},
{it:"istante",de:"sofort",cat:"Substantive"},
{it:"lago",de:"See",cat:"Substantive"},
{it:"italiano",de:"Italienisch",cat:"Adjektive"},
{it:"ultimo",de:"zuletzt",cat:"Adjektive"},
{it:"vecchio",de:"alt",cat:"Adjektive"},
{it:"piccolo",de:"klein",cat:"Adjektive"},
{it:"troppo",de:"zu viel",cat:"Adjektive"},
{it:"tale",de:"solch",cat:"Adjektive"},
{it:"giovane",de:"jung",cat:"Adjektive"},
{it:"alto",de:"groß",cat:"Adjektive"},
{it:"vostro",de:"dein/Ihr",cat:"Adjektive"},
{it:"diverso",de:"anders",cat:"Adjektive"},
{it:"meglio",de:"besser",cat:"Adjektive"},
{it:"lungo",de:"lang",cat:"Adjektive"},
{it:"povero",de:"arm",cat:"Adjektive"},
{it:"maggiore",de:"größer",cat:"Adjektive"},
{it:"secondo",de:"zweite",cat:"Adjektive"},
{it:"lontano",de:"weit",cat:"Adjektive"},
{it:"vicino",de:"schließen",cat:"Adjektive"},
{it:"possibile",de:"möglich",cat:"Adjektive"},
{it:"caro",de:"Liebling",cat:"Adjektive"},
{it:"pieno",de:"voll",cat:"Adjektive"},
{it:"nero",de:"Schwarz",cat:"Adjektive"},
{it:"particolare",de:"besondere",cat:"Adjektive"},
{it:"bianco",de:"Weiß",cat:"Adjektive"},
{it:"forte",de:"stark",cat:"Adjektive"},
{it:"politico",de:"Politik",cat:"Adjektive"},
{it:"attuale",de:"aktuell",cat:"Adjektive"},
{it:"latino",de:"lateinisch",cat:"Adjektive"},
{it:"impossibile",de:"unmöglich",cat:"Adjektive"},
{it:"giallo",de:"Gelb",cat:"Adjektive"},
{it:"pazzo",de:"verrückt",cat:"Adjektive"},
{it:"sacro",de:"heilig",cat:"Adjektive"},
{it:"comodo",de:"komfortabel",cat:"Adjektive"},
{it:"elettrico",de:"elektrisch",cat:"Adjektive"},
{it:"assoluto",de:"Absolute",cat:"Adjektive"},
{it:"cristiano",de:"Christian",cat:"Adjektive"},
{it:"antico",de:"uralt",cat:"Adjektive"},
{it:"rosso",de:"Rot",cat:"Adjektive"},
{it:"chiaro",de:"klar",cat:"Adjektive"},
{it:"unico",de:"einzel",cat:"Adjektive"},
{it:"sicuro",de:"Sicher",cat:"Adjektive"},
{it:"importante",de:"wichtig",cat:"Adjektive"},
{it:"vario",de:"abwechslungsreich",cat:"Adjektive"},
{it:"giusto",de:"ganz richtig",cat:"Adjektive"},
{it:"francese",de:"Französisch",cat:"Adjektive"},
{it:"vivo",de:"Ich lebe",cat:"Adjektive"},
{it:"generale",de:"allgemein",cat:"Adjektive"},
{it:"ricco",de:"reich",cat:"Adjektive"},
{it:"grosso",de:"groß",cat:"Adjektive"},
{it:"necessario",de:"notwendig",cat:"Adjektive"},
{it:"libero",de:"frei",cat:"Adjektive"},
{it:"nazionale",de:"national",cat:"Adjektive"},
{it:"basso",de:"Bass",cat:"Adjektive"},
{it:"semplice",de:"einfach",cat:"Adjektive"},
{it:"grave",de:"ernst",cat:"Adjektive"},
{it:"comune",de:"gemeinsam",cat:"Adjektive"},
{it:"freddo",de:"kalt",cat:"Adjektive"},
{it:"storico",de:"historisch",cat:"Adjektive"},
{it:"superiore",de:"höher",cat:"Adjektive"},
{it:"inglese",de:"schwierig",cat:"Adjektive"},
{it:"fermo",de:"stationär",cat:"Adjektive"},
{it:"solito",de:"üblich",cat:"Adjektive"},
{it:"buio",de:"dunkel",cat:"Adjektive"},
{it:"strano",de:"seltsam",cat:"Adjektive"},
{it:"noto",de:"bekannt",cat:"Adjektive"},
{it:"prossimo",de:"Nächstes",cat:"Adjektive"},
{it:"profondo",de:"tief",cat:"Adjektive"},
{it:"sociale",de:"sozial",cat:"Adjektive"},
{it:"cattivo",de:"schlecht",cat:"Adjektive"},
{it:"massimo",de:"maximal",cat:"Adjektive"},
{it:"intero",de:"voll",cat:"Adjektive"},
{it:"uguale",de:"gleich",cat:"Adjektive"},
{it:"bravo",de:"guter Junge",cat:"Adjektive"},
{it:"brutto",de:"hässlich",cat:"Adjektive"},
{it:"preciso",de:"genau",cat:"Adjektive"},
{it:"qualsiasi",de:"beliebig",cat:"Adjektive"},
{it:"improvviso",de:"plötzlich",cat:"Adjektive"},
{it:"famoso",de:"berühmt",cat:"Adjektive"},
{it:"straniero",de:"Ausländer",cat:"Adjektive"},
{it:"civile",de:"bürgerlich",cat:"Adjektive"},
{it:"internazionale",de:"international",cat:"Adjektive"},
{it:"interno",de:"intern",cat:"Adjektive"},
{it:"vasto",de:"umfangreich",cat:"Adjektive"},
{it:"segreto",de:"Geheimnis",cat:"Adjektive"},
{it:"greco",de:"griechisch",cat:"Adjektive"},
{it:"naturale",de:"natürlich",cat:"Adjektive"},
{it:"sinistro",de:"links",cat:"Adjektive"},
{it:"duro",de:"hart",cat:"Adjektive"},
{it:"stanco",de:"müde",cat:"Adjektive"},
{it:"azzurro",de:"hellblau",cat:"Adjektive"},
{it:"recente",de:"jüngste",cat:"Adjektive"},
{it:"notevole",de:"bemerkenswert",cat:"Adjektive"},
{it:"cittadino",de:"Bürger",cat:"Adjektive"},
{it:"destro",de:"Rechts",cat:"Adjektive"},
{it:"europeo",de:"europäisch",cat:"Adjektive"},
{it:"zitto",de:"ruhig",cat:"Adjektive"},
{it:"medio",de:"Durchschnitt",cat:"Adjektive"},
{it:"qualunque",de:"was auch immer",cat:"Adjektive"},
{it:"straordinario",de:"außergewöhnlich",cat:"Adjektive"},
{it:"nudo",de:"nackt",cat:"Adjektive"},
{it:"futuro",de:"Zukunft",cat:"Adjektive"},
{it:"cattolico",de:"katholisch",cat:"Adjektive"},
{it:"capace",de:"fähig",cat:"Adjektive"},
{it:"industriale",de:"industriell",cat:"Adjektive"},
{it:"personale",de:"Personal",cat:"Adjektive"},
{it:"centrale",de:"zentral",cat:"Adjektive"},
{it:"tecnico",de:"technisch",cat:"Adjektive"},
{it:"dolce",de:"süß",cat:"Adjektive"},
{it:"leggero",de:"Licht",cat:"Adjektive"},
{it:"morale",de:"Moral",cat:"Adjektive"},
{it:"utile",de:"hilfreich",cat:"Adjektive"},
{it:"contrario",de:"Gegenteil",cat:"Adjektive"},
{it:"speciale",de:"besonders",cat:"Adjektive"},
{it:"peggio",de:"schlechter",cat:"Adjektive"},
{it:"minore",de:"untere",cat:"Adjektive"},
{it:"contadino",de:"Bauer",cat:"Adjektive"},
{it:"chiamare",de:"anrufen",cat:"Verben"},
{it:"conoscere",de:"wissen",cat:"Verben"},
{it:"rimanere",de:"bleiben",cat:"Verben"},
{it:"chiedere",de:"fragen",cat:"Verben"},
{it:"cercare",de:"suchen",cat:"Verben"},
{it:"entrare",de:"hereinkommen",cat:"Verben"},
{it:"vivere",de:"leben",cat:"Verben"},
{it:"aprire",de:"zu öffnen",cat:"Verben"},
{it:"uscire",de:"ausgehen",cat:"Verben"},
{it:"ricordare",de:"zu erinnern",cat:"Verben"},
{it:"bisognare",de:"brauchen",cat:"Verben"},
{it:"cominciare",de:"beginnen",cat:"Verben"},
{it:"rispondere",de:"antworten, antworten",cat:"Verben"},
{it:"aspettare",de:"warten",cat:"Verben"},
{it:"riuscire",de:"erfolgreich zu sein",cat:"Verben"},
{it:"chiudere",de:"schließen",cat:"Verben"},
{it:"finire",de:"zum Abschluss",cat:"Verben"},
{it:"arrivare",de:"ankommen",cat:"Verben"},
{it:"scrivere",de:"schreiben",cat:"Verben"},
{it:"diventare",de:"to become",cat:"Verben"},
{it:"restare",de:"bleiben",cat:"Verben"},
{it:"seguire",de:"folgen",cat:"Verben"},
{it:"bastare",de:"genügen",cat:"Verben"},
{it:"perdere",de:"verlieren",cat:"Verben"},
{it:"rendere",de:"machen (groß, klein...)",cat:"Verben"},
{it:"correre",de:"laufen",cat:"Verben"},
{it:"salvare",de:"zu retten",cat:"Verben"},
{it:"vestire",de:"anziehen",cat:"Verben"},
{it:"costruire",de:"zu bauen",cat:"Verben"},
{it:"scusare",de:"entschuldigen",cat:"Verben"},
{it:"mantenere",de:"zu pflegen",cat:"Verben"},
{it:"ritenere",de:"zu berücksichtigen",cat:"Verben"},
{it:"concludere",de:"zum Abschluss",cat:"Verben"},
{it:"saltare",de:"springen",cat:"Verben"},
{it:"stabilire",de:"zu etablieren",cat:"Verben"},
{it:"appartenere",de:"dazugehören",cat:"Verben"},
{it:"possedere",de:"besitzen",cat:"Verben"},
{it:"risultare",de:"ergeben",cat:"Verben"},
{it:"suonare",de:"zu spielen",cat:"Verben"},
{it:"coprire",de:"zu vertuschen",cat:"Verben"},
{it:"insegnare",de:"zu lehren",cat:"Verben"},
{it:"affermare",de:"behaupten",cat:"Verben"},
{it:"rivelare",de:"zu enthüllen",cat:"Verben"},
{it:"conservare",de:"zu bewahren",cat:"Verben"},
{it:"risolvere",de:"zu lösen",cat:"Verben"},
{it:"concedere",de:"gewähren",cat:"Verben"},
{it:"limitare",de:"begrenzen",cat:"Verben"},
{it:"abitare",de:"leben",cat:"Verben"},
{it:"convincere",de:"überzeugen",cat:"Verben"},
{it:"comprare",de:"zu kaufen",cat:"Verben"},
{it:"legare",de:"binden",cat:"Verben"},
{it:"sostenere",de:"zu erhalten",cat:"Verben"},
{it:"nascere",de:"geboren werden",cat:"Verben"},
{it:"presentare",de:"vorstellen",cat:"Verben"},
{it:"trattare",de:"umzugehen",cat:"Verben"},
{it:"continuare",de:"weitermachen",cat:"Verben"},
{it:"partire",de:"gehen",cat:"Verben"},
{it:"decidere",de:"zu entscheiden",cat:"Verben"},
{it:"ricevere",de:"zu empfangen",cat:"Verben"},
{it:"osservare",de:"zu beobachten",cat:"Verben"},
{it:"permettere",de:"erlauben",cat:"Verben"},
{it:"avvenire",de:"auftreten",cat:"Verben"},
{it:"spiegare",de:"zu erklären",cat:"Verben"},
{it:"raccogliere",de:"sammeln",cat:"Verben"},
{it:"ottenere",de:"zu erhalten",cat:"Verben"},
{it:"offrire",de:"zu bieten",cat:"Verben"},
{it:"mostrare",de:"auszustellen",cat:"Verben"},
{it:"accompagnare",de:"begleiten",cat:"Verben"},
{it:"dimenticare",de:"vergessen",cat:"Verben"},
{it:"pregare",de:"beten",cat:"Verben"},
{it:"raccontare",de:"erzählen",cat:"Verben"},
{it:"bere",de:"zum Trinken",cat:"Verben"},
{it:"ritornare",de:"zurückkehren",cat:"Verben"},
{it:"cambiare",de:"ändern",cat:"Verben"},
{it:"dimostrare",de:"zu demonstrieren",cat:"Verben"},
{it:"sperare",de:"hoffen",cat:"Verben"},
{it:"sposare",de:"heiraten",cat:"Verben"},
{it:"ammettere",de:"zugeben",cat:"Verben"},
{it:"fuggire",de:"weglaufen",cat:"Verben"},
{it:"liberare",de:"zu befreien",cat:"Verben"},
{it:"riferire",de:"zu berichten",cat:"Verben"},
{it:"svegliare",de:"aufwachen",cat:"Verben"},
{it:"capitare",de:"passieren",cat:"Verben"},
{it:"posare",de:"platzieren",cat:"Verben"},
{it:"impedire",de:"zu verhindern",cat:"Verben"},
{it:"gettare",de:"werfen",cat:"Verben"},
{it:"esporre",de:"entlarven",cat:"Verben"},
{it:"attraversare",de:"gehen über",cat:"Verben"},
{it:"fornire",de:"bereitzustellen",cat:"Verben"},
{it:"segnare",de:"markieren",cat:"Verben"},
{it:"superare",de:"zu überwinden",cat:"Verben"},
{it:"rivedere",de:"zu überprüfen",cat:"Verben"},
{it:"allontanare",de:"zu entfernen",cat:"Verben"},
{it:"ammazzare",de:"töten",cat:"Verben"},
{it:"accogliere",de:"zu empfangen",cat:"Verben"},
{it:"voltare",de:"umdrehen",cat:"Verben"},
{it:"preoccupare",de:"sich Sorgen machen",cat:"Verben"},
{it:"provocare",de:"verursachen",cat:"Verben"},
{it:"riempire",de:"füllen",cat:"Verben"},
{it:"partecipare",de:"teilnehmen",cat:"Verben"},
{it:"piantare",de:"pflanzen",cat:"Verben"},
{it:"rientrare",de:"wieder eintreten",cat:"Verben"},
{it:"richiedere",de:"anzufordern",cat:"Verben"},
{it:"nascondere",de:"verstecken",cat:"Verben"},
{it:"ripetere",de:"wiederholen",cat:"Verben"},
{it:"scoprire",de:"zu entdecken",cat:"Verben"},
{it:"preparare",de:"vorbereiten",cat:"Verben"},
{it:"scorrere",de:"gleiten",cat:"Verben"},
{it:"rappresentare",de:"repräsentieren",cat:"Verben"},
{it:"riprendere",de:"fortfahren",cat:"Verben"},
{it:"costituire",de:"konstituieren",cat:"Verben"},
{it:"incontrare",de:"zu treffen",cat:"Verben"},
{it:"valere",de:"wert sein",cat:"Verben"},
{it:"accorgersi",de:"bemerken",cat:"Verben"},
{it:"provare",de:"zu versuchen",cat:"Verben"},
{it:"riguardare",de:"beunruhigen",cat:"Verben"},
{it:"rivolgere",de:"umdrehen",cat:"Verben"},
{it:"tacere",de:"schweigen",cat:"Verben"},
{it:"occorrere",de:"nehmen",cat:"Verben"},
{it:"porre",de:"platzieren",cat:"Verben"},
{it:"vincere",de:"gewinnen",cat:"Verben"},
{it:"svolgere",de:"durchführen",cat:"Verben"},
{it:"studiare",de:"zu studieren",cat:"Verben"},
{it:"crescere",de:"erwachsen werden",cat:"Verben"},
{it:"divenire",de:"to become",cat:"Verben"},
{it:"gridare",de:"schreien",cat:"Verben"},
{it:"dichiarare",de:"zu erklären",cat:"Verben"},
{it:"contare",de:"zählen",cat:"Verben"},
{it:"giocare",de:"zu spielen",cat:"Verben"},
{it:"assistere",de:"zu helfen",cat:"Verben"},
{it:"aumentare",de:"erhöhen",cat:"Verben"},
{it:"lanciare",de:"starten",cat:"Verben"},
{it:"determinare",de:"zu bestimmen",cat:"Verben"},
{it:"scherzare",de:"scherzen",cat:"Verben"},
{it:"elevare",de:"erhöhen",cat:"Verben"},
{it:"promettere",de:"versprechen",cat:"Verben"},
{it:"scomparire",de:"verschwinden",cat:"Verben"},
{it:"trarre",de:"zeichnen",cat:"Verben"},
{it:"distruggere",de:"zu zerstören",cat:"Verben"},
{it:"meritare",de:"verdienen",cat:"Verben"},
{it:"dedicare",de:"widmen",cat:"Verben"},
{it:"iniziare",de:"beginnen",cat:"Verben"},
{it:"sorprendere",de:"überraschen",cat:"Verben"},
{it:"trasformare",de:"pendeln",cat:"Verben"},
{it:"estendere",de:"verlängern",cat:"Verben"},
{it:"staccare",de:"zu entfernen",cat:"Verben"},
{it:"affrontare",de:"sich stellen",cat:"Verben"},
{it:"avanzare",de:"vorantreiben",cat:"Verben"},
{it:"comporre",de:"komponieren",cat:"Verben"},
{it:"escludere",de:"auszuschließen",cat:"Verben"},
{it:"figurare",de:"erscheinen",cat:"Verben"},
{it:"insistere",de:"darauf bestehen",cat:"Verben"},
{it:"opporre",de:"widersprechen",cat:"Verben"},
{it:"procedere",de:"fortfahren",cat:"Verben"},
{it:"smettere",de:"aufzuhören",cat:"Verben"},
{it:"consentire",de:"erlauben",cat:"Verben"},
{it:"innamorarsi",de:"sich verlieben",cat:"Verben"},
{it:"organizzare",de:"zu organisieren",cat:"Verben"},
{it:"rifiutare",de:"abzulehnen",cat:"Verben"},
{it:"riportare",de:"zu berichten",cat:"Verben"},
{it:"dipendere",de:"abhängen",cat:"Verben"},
{it:"provvedere",de:"bereitzustellen",cat:"Verben"},
{it:"trascinare",de:"ziehen",cat:"Verben"},
{it:"fumare",de:"rauchen",cat:"Verben"},
{it:"scoppiare",de:"platzen",cat:"Verben"},
{it:"sognare",de:"träumen",cat:"Verben"},
{it:"appoggiare",de:"zu unterstützen",cat:"Verben"},
{it:"armare",de:"bewaffnen",cat:"Verben"},
{it:"celebrare",de:"zu feiern",cat:"Verben"},
{it:"descrivere",de:"zu beschreiben",cat:"Verben"},
{it:"resistere",de:"widerstehen",cat:"Verben"},
{it:"bruciare",de:"brennen",cat:"Verben"},
{it:"colpire",de:"schlagen",cat:"Verben"},
{it:"senza",de:"ohne",cat:"Sonstige"},
{it:"cui",de:"welche",cat:"Sonstige"},
{it:"chi",de:"WHO",cat:"Sonstige"},
{it:"già",de:"bereits",cat:"Sonstige"},
{it:"dopo",de:"nach",cat:"Sonstige"},
{it:"uno",de:"eins",cat:"Sonstige"},
{it:"noi",de:"wir",cat:"Sonstige"},
{it:"dove",de:"Wo",cat:"Sonstige"},
{it:"qui",de:"Hier",cat:"Sonstige"},
{it:"no",de:"NEIN",cat:"Sonstige"},
{it:"allora",de:"Dann",cat:"Sonstige"},
{it:"tra",de:"zwischen",cat:"Sonstige"},
{it:"vi",de:"du/Sie",cat:"Sonstige"},
{it:"ora",de:"Jetzt",cat:"Sonstige"},
{it:"fra",de:"zwischen",cat:"Sonstige"},
{it:"prima",de:"vor",cat:"Sonstige"},
{it:"forse",de:"vielleicht",cat:"Sonstige"},
{it:"sì",de:"Ja",cat:"Sonstige"},
{it:"sotto",de:"unter",cat:"Sonstige"},
{it:"voi",de:"du/Sie",cat:"Sonstige"},
{it:"fino",de:"bis",cat:"Sonstige"},
{it:"oggi",de:"Heute",cat:"Sonstige"},
{it:"quasi",de:"fast",cat:"Sonstige"},
{it:"pure",de:"Auch",cat:"Sonstige"},
{it:"egli",de:"er",cat:"Sonstige"},
{it:"mentre",de:"während",cat:"Sonstige"},
{it:"contro",de:"gegen",cat:"Sonstige"},
{it:"invece",de:"stattdessen",cat:"Sonstige"},
{it:"oltre",de:"über",cat:"Sonstige"},
{it:"intorno",de:"um",cat:"Sonstige"},
{it:"sopra",de:"über",cat:"Sonstige"},
{it:"dietro",de:"hinter",cat:"Sonstige"},
{it:"davanti",de:"vor",cat:"Sonstige"},
{it:"soltanto",de:"nur",cat:"Sonstige"},
{it:"infatti",de:"In der Tat",cat:"Sonstige"},
{it:"qualcosa",de:"etwas",cat:"Sonstige"},
{it:"spesso",de:"oft",cat:"Sonstige"},
{it:"accordo",de:"Vereinbarung",cat:"Sonstige"},
{it:"ieri",de:"gestern",cat:"Sonstige"},
{it:"davvero",de:"Wirklich",cat:"Sonstige"},
{it:"lì",de:"Dort",cat:"Sonstige"},
{it:"qualcuno",de:"jemand",cat:"Sonstige"},
{it:"avanti",de:"Komm schon",cat:"Sonstige"},
{it:"assai",de:"sehr",cat:"Sonstige"},
{it:"presto",de:"bald",cat:"Sonstige"},
{it:"qua",de:"Hier",cat:"Sonstige"},
{it:"domani",de:"morgen",cat:"Sonstige"},
{it:"circa",de:"um",cat:"Sonstige"},
{it:"giù",de:"runter",cat:"Sonstige"},
{it:"soprattutto",de:"meistens",cat:"Sonstige"},
{it:"nemmeno",de:"nicht einmal",cat:"Sonstige"},
{it:"grazie",de:"Danke",cat:"Sonstige"},
{it:"tuttavia",de:"Jedoch",cat:"Sonstige"},
{it:"appunto",de:"Nur",cat:"Sonstige"},
{it:"neppure",de:"weder",cat:"Sonstige"},
{it:"eh",de:"huh",cat:"Sonstige"},
{it:"veramente",de:"Wirklich",cat:"Sonstige"},
{it:"finché",de:"solange",cat:"Sonstige"},
{it:"perfino",de:"sogar",cat:"Sonstige"},
{it:"affatto",de:"überhaupt",cat:"Sonstige"},
{it:"stamattina",de:"Heute Morgen",cat:"Sonstige"},
{it:"completamente",de:"vollständig",cat:"Sonstige"},
{it:"probabilmente",de:"wahrscheinlich",cat:"Sonstige"},
{it:"chissà",de:"Wer weiß",cat:"Sonstige"},
{it:"ognuno",de:"jeder",cat:"Sonstige"},
{it:"entro",de:"innerhalb",cat:"Sonstige"},
{it:"naturalmente",de:"Natürlich",cat:"Sonstige"},
{it:"accanto",de:"nächste",cat:"Sonstige"},
{it:"eppure",de:"aber doch",cat:"Sonstige"},
{it:"eccetera",de:"usw",cat:"Sonstige"},
{it:"finalmente",de:"Endlich",cat:"Sonstige"},
{it:"infine",de:"Endlich",cat:"Sonstige"},
{it:"poiché",de:"als",cat:"Sonstige"},
{it:"comunque",de:"Jedoch",cat:"Sonstige"},
{it:"dinanzi",de:"vor",cat:"Sonstige"},
{it:"abbastanza",de:"genug",cat:"Sonstige"},
{it:"peccato",de:"Sünde",cat:"Sonstige"},
{it:"certamente",de:"Natürlich",cat:"Sonstige"},
{it:"coloro",de:"sie",cat:"Sonstige"},
{it:"attorno",de:"um",cat:"Sonstige"},
{it:"magari",de:"Vielleicht",cat:"Sonstige"},
{it:"oppure",de:"oder",cat:"Sonstige"},
{it:"inoltre",de:"Außerdem",cat:"Sonstige"},
{it:"indietro",de:"zurück",cat:"Sonstige"},
{it:"addosso",de:"An",cat:"Sonstige"},
{it:"addirittura",de:"sogar",cat:"Sonstige"},
];

const CONJUGATIONS = {
  "essere":{"io":"sono","tu":"sei","lui":"è","noi":"siamo","voi":"siete","loro":"sono"},
  "avere":{"io":"ho","tu":"hai","lui":"ha","noi":"abbiamo","voi":"avete","loro":"hanno"},
  "andare":{"io":"vado","tu":"vai","lui":"va","noi":"andiamo","voi":"andate","loro":"vanno"},
  "fare":{"io":"faccio","tu":"fai","lui":"fa","noi":"facciamo","voi":"fate","loro":"fanno"},
  "potere":{"io":"posso","tu":"puoi","lui":"può","noi":"possiamo","voi":"potete","loro":"possono"},
  "volere":{"io":"voglio","tu":"vuoi","lui":"vuole","noi":"vogliamo","voi":"volete","loro":"vogliono"},
  "dovere":{"io":"devo","tu":"devi","lui":"deve","noi":"dobbiamo","voi":"dovete","loro":"devono"},
  "sapere":{"io":"so","tu":"sai","lui":"sa","noi":"sappiamo","voi":"sapete","loro":"sanno"},
  "stare":{"io":"sto","tu":"stai","lui":"sta","noi":"stiamo","voi":"state","loro":"stanno"},
  "dire":{"io":"dico","tu":"dici","lui":"dice","noi":"diciamo","voi":"dite","loro":"dicono"},
  "bere":{"io":"bevo","tu":"bevi","lui":"beve","noi":"beviamo","voi":"bevete","loro":"bevono"},
  "dare":{"io":"do","tu":"dai","lui":"dà","noi":"diamo","voi":"date","loro":"danno"},
  "venire":{"io":"vengo","tu":"vieni","lui":"viene","noi":"veniamo","voi":"venite","loro":"vengono"},
  "porre":{"io":"pongo","tu":"poni","lui":"pone","noi":"poniamo","voi":"ponete","loro":"pongono"},
  "uscire":{"io":"esco","tu":"esci","lui":"esce","noi":"usciamo","voi":"uscite","loro":"escono"},
  "rimanere":{"io":"rimango","tu":"rimani","lui":"rimane","noi":"rimaniamo","voi":"rimanete","loro":"rimangono"},
  "scegliere":{"io":"scelgo","tu":"scegli","lui":"sceglie","noi":"scegliamo","voi":"scegliete","loro":"scelgono"},
  "piacere":{"io":"piaccio","tu":"piaci","lui":"piace","noi":"piacciamo","voi":"piacete","loro":"piacciono"},
  "valere":{"io":"valgo","tu":"vali","lui":"vale","noi":"valiamo","voi":"valete","loro":"valgono"},
  "morire":{"io":"muoio","tu":"muori","lui":"muore","noi":"moriamo","voi":"morite","loro":"muoiono"},
  "tradurre":{"io":"traduco","tu":"traduci","lui":"traduce","noi":"traduciamo","voi":"traducete","loro":"traducono"},
  "salire":{"io":"salgo","tu":"sali","lui":"sale","noi":"saliamo","voi":"salite","loro":"salgono"},
  "sparire":{"io":"sparisco","tu":"sparisci","lui":"sparisce","noi":"spariamo","voi":"sparite","loro":"spariscono"}
};

const CONJ_PERSONS = ["io","tu","lui/lei","noi","voi","loro"];
